//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandbox.QuickTests.AdventOfCode.Y2023.DayOne {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sandbox.QuickTests.AdventOfCode.Y2023.DayOne.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixrrmlkptmc18zhvninek
        ///jcb82eightwond
        ///twofourthree778nineeight
        ///sqpxs1cgcrmctlgqvzxbcjzgr
        ///nqkjxbmbpkz9eight8
        ///one6fourfiveqndtrvgkkgthppnine
        ///zbrbdpbfcfxcqq5oneninejfgqpkfn
        ///hvlstzgvmjfivefourqjqtxdjmbxfour4four2
        ///13dzbmbtl6
        ///fourone2pmlxzzbmnfxg2
        ///3fourrbvvlrsrbb2858
        ///vlz4six89
        ///75threeb
        ///fourp783fiveseventhree
        ///2gxvcbsmn6
        ///896
        ///dnblxtxxpstlsix56
        ///4fivecl185
        ///onefk8sdljtfv37zsxsxrv7qvrpnmd
        ///fourdvhzp7foursix
        ///seventwonineseven27jbrqpxfx8
        ///1threenine241gnrdfqn5
        ///sixnrsqdgmkvs7sevenkgjgtglmdq9dkdzsdqmq2np [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PartOne {
            get {
                return ResourceManager.GetString("PartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two1nine
        ///eightwothree
        ///abcone2threexyz
        ///xtwone3four
        ///4nineeightseven2
        ///zoneight234
        ///7pqrstsixteen.
        /// </summary>
        internal static string PartTwo {
            get {
                return ResourceManager.GetString("PartTwo", resourceCulture);
            }
        }
    }
}
